spring:
  application:
    name: sample4guide

  datasource:
    url: jdbc:h2:mem:test # h2 support in-memory-db
    username: lshh
    password: lshh.com
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
